### ISSUE TITLE
cannot find S3 

### ISSUE THREAD

**Issue by cristianmtr** [jina-ai/cloud-helper#5]
Installed via `$ pip install -e git://github.com/jina-ai/cloud-helper.git#egg=jinacld_tools` but not working.

Python 3.7

```
Traceback (most recent call last):
  File "../util/pull_dataset.py", line 6, in <module>
    from jinacld_tools.aws.services.s3 import S3
ImportError: cannot import name 'S3' from 'jinacld_tools.aws.services.s3' (/home/cristian/envs/example-object-detection/src/jinacld-tools/src/jinacld_tools/aws/services/s3.py)
```

**Comment by slettner** [comment]
Hi Christian, 

the class has been renamed after version 0.0.1 from `S3` to `S3Bucket`. 

If you install with 
`pip install -e git://github.com/jina-ai/cloud-helper.git#egg=jinacld_tools` the most recent master branch is installed, that is why the `S3` is not available.

If installed with the Tag specified, it will work 
`pip install -e git://github.com/jina-ai/cloud-helper.git@v0.0.1#egg=jinacld_tools`

**Comment by slettner** [comment]
I will bump the version and make a PR against examples repository to use the new code.

**Comment by slettner** [comment]
Closing issue after examples repository has been updated (https://github.com/jina-ai/examples/pull/617)
